name: 'Renew EUserv'

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  schedule:
    - cron: '11 12 1 * *'


permissions:
  contents: write

jobs:
        
  auto_renew:
    runs-on: ubuntu-latest
    environment: production
    steps:  
      - name: 'Checkout codes'
        uses: actions/checkout@v4

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: 'latest' # Options: 'latest', 'latest-esr', or specific versions like '120.0'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade google-api-python-client
          python -m pip install --upgrade google-auth-httplib2 
          python -m pip install --upgrade google-auth-oauthlib
          python -m pip install --upgrade requests
          python -m pip install --upgrade beautifulsoup4
          python -m pip install --upgrade pysocks
          python -m pip install --upgrade Pillow
          python -m pip install --upgrade openai

      - name: 'Auto_renew'
        env:
          EUSERV_USERNAME: ${{ secrets.EUSERV_USERNAME }}
          EUSERV_PASSWORD: ${{ secrets.EUSERV_PASSWORD }}
          TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}
          TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
        run: python eu.py
        
