name: 'Test Gmail API'

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #schedule:
  #  - cron: '50 4 * * *'


permissions:
  contents: write

jobs:
  gmail_refresh:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v4

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: 'latest' # Options: 'latest', 'latest-esr', or specific versions like '120.0'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade google-api-python-client
          python -m pip install --upgrade google-auth-httplib2 
          python -m pip install --upgrade google-auth-oauthlib
          python -m pip install --upgrade requests
          python -m pip install --upgrade beautifulsoup4
          python -m pip install --upgrade pysocks

      - name: 'refresh credantial'
        run: python gmail_api.py stayawake.xc@gmail.com
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest gmailapi'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
